
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package josq.cms.lenguajes.automatas;

/** CUP generated interface containing symbol constants. */
public interface ParserComandosSym {
  /* terminals */
  public static final int CONSULT = 2;
  public static final int VIDEO = 15;
  public static final int PAGE_VIEWS = 8;
  public static final int MENU = 13;
  public static final int SITE_VIEWS = 7;
  public static final int PAGE_POP = 9;
  public static final int TITULO = 12;
  public static final int COMP = 10;
  public static final int ID = 17;
  public static final int DOT = 6;
  public static final int COMI = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int PUNCOM = 3;
  public static final int IMAGEN = 14;
  public static final int PARRAFO = 16;
  public static final int TODOS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSULT",
  "PUNCOM",
  "COMI",
  "COMA",
  "DOT",
  "SITE_VIEWS",
  "PAGE_VIEWS",
  "PAGE_POP",
  "COMP",
  "TODOS",
  "TITULO",
  "MENU",
  "IMAGEN",
  "VIDEO",
  "PARRAFO",
  "ID"
  };
}

