
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package josq.cms.lenguajes.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserAccionesSym {
  /* terminals */
  public static final int P_FECHA_MOD = 35;
  public static final int A_ETIQS = 50;
  public static final int A_ORIGEN = 46;
  public static final int UI_VIDEO = 41;
  public static final int A_TEXTO = 43;
  public static final int COMP_DEL = 26;
  public static final int P_SITIO = 30;
  public static final int MI_TEXTO = 56;
  public static final int NOMBRE = 19;
  public static final int A_ALTO = 47;
  public static final int A_ALIGN = 44;
  public static final int UI_MENU = 42;
  public static final int MI_ETIQUETA = 61;
  public static final int ACCIS = 10;
  public static final int PARAM = 13;
  public static final int ACCI = 11;
  public static final int P_ID = 28;
  public static final int IGUAL = 5;
  public static final int IZQ = 2;
  public static final int ATRIBS = 14;
  public static final int A_ANCHO = 48;
  public static final int MI_ID = 55;
  public static final int OR = 9;
  public static final int MI_URL = 59;
  public static final int MI_FECHA = 60;
  public static final int DERCOR = 7;
  public static final int COMI = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int UI_TITULO = 38;
  public static final int P_PAGINA = 32;
  public static final int T_CENTRAR = 51;
  public static final int T_IZQUIERDA = 52;
  public static final int A_PADRE = 49;
  public static final int P_USER_NEW = 36;
  public static final int PARAMS = 12;
  public static final int P_PADRE = 31;
  public static final int SITE_NEW = 20;
  public static final int T_JUSTIFICAR = 54;
  public static final int P_USER_MOD = 37;
  public static final int ATRIB = 15;
  public static final int BARRA = 4;
  public static final int VALOR = 18;
  public static final int PAGE_NEW = 22;
  public static final int DER = 3;
  public static final int PAGE_MOD = 24;
  public static final int P_CLASE = 33;
  public static final int MI_NUMERO = 57;
  public static final int COMP_NEW = 25;
  public static final int ETIQS = 16;
  public static final int A_COLOR = 45;
  public static final int MI_COLOR = 58;
  public static final int UI_IMAGEN = 40;
  public static final int P_TITULO = 29;
  public static final int COMP_MOD = 27;
  public static final int IZQCOR = 6;
  public static final int ETIQ = 17;
  public static final int UI_PARRAFO = 39;
  public static final int T_DERECHA = 53;
  public static final int SITE_DEL = 21;
  public static final int P_FECHA_NEW = 34;
  public static final int PAGE_DEL = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IZQ",
  "DER",
  "BARRA",
  "IGUAL",
  "IZQCOR",
  "DERCOR",
  "COMI",
  "OR",
  "ACCIS",
  "ACCI",
  "PARAMS",
  "PARAM",
  "ATRIBS",
  "ATRIB",
  "ETIQS",
  "ETIQ",
  "VALOR",
  "NOMBRE",
  "SITE_NEW",
  "SITE_DEL",
  "PAGE_NEW",
  "PAGE_DEL",
  "PAGE_MOD",
  "COMP_NEW",
  "COMP_DEL",
  "COMP_MOD",
  "P_ID",
  "P_TITULO",
  "P_SITIO",
  "P_PADRE",
  "P_PAGINA",
  "P_CLASE",
  "P_FECHA_NEW",
  "P_FECHA_MOD",
  "P_USER_NEW",
  "P_USER_MOD",
  "UI_TITULO",
  "UI_PARRAFO",
  "UI_IMAGEN",
  "UI_VIDEO",
  "UI_MENU",
  "A_TEXTO",
  "A_ALIGN",
  "A_COLOR",
  "A_ORIGEN",
  "A_ALTO",
  "A_ANCHO",
  "A_PADRE",
  "A_ETIQS",
  "T_CENTRAR",
  "T_IZQUIERDA",
  "T_DERECHA",
  "T_JUSTIFICAR",
  "MI_ID",
  "MI_TEXTO",
  "MI_NUMERO",
  "MI_COLOR",
  "MI_URL",
  "MI_FECHA",
  "MI_ETIQUETA"
  };
}

