
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package josq.cms.lenguajes.parser;

import josq.cms.lenguajes.modelos.arbol.*;
import josq.cms.lenguajes.modelos.Indicador;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAcciones extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserAccionesSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAcciones() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAcciones(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAcciones(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\132\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\005\000\002\004\005\000\002\005\003" +
    "\000\002\005\004\000\002\006\006\000\002\007\005\000" +
    "\002\010\006\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\004\000\002\011\004\000\002\011" +
    "\004\000\002\012\006\000\002\013\007\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\015\005\000\002\016\005\000\002\017" +
    "\003\000\002\017\004\000\002\020\006\000\002\021\005" +
    "\000\002\022\006\000\002\023\005\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\024\006\000\002\025\007\000\002\027\003" +
    "\000\002\027\003\000\002\027\003\000\002\027\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\030" +
    "\005\000\002\031\005\000\002\032\003\000\002\032\004" +
    "\000\002\033\006\000\002\034\005\000\002\035\006\000" +
    "\002\036\005\000\002\041\003\000\002\041\003\000\002" +
    "\041\003\000\002\041\003\000\002\041\003\000\002\041" +
    "\003\000\002\041\003\000\002\041\003\000\002\041\003" +
    "\000\002\051\003\000\002\051\005\000\002\037\006\000" +
    "\002\040\007\000\002\042\003\000\002\042\003\000\002" +
    "\042\003\000\002\042\003\000\002\042\003\000\002\042" +
    "\003\000\002\042\003\000\002\042\003\000\002\043\005" +
    "\000\002\044\005\000\002\045\003\000\002\045\004\000" +
    "\002\046\006\000\002\047\007\000\002\050\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\247\000\004\004\007\001\002\000\004\002\uffff\001" +
    "\002\000\004\002\251\001\002\000\004\002\000\001\002" +
    "\000\006\014\247\015\020\001\002\000\004\004\051\001" +
    "\002\000\004\004\013\001\002\000\004\004\ufffc\001\002" +
    "\000\004\015\020\001\002\000\004\004\016\001\002\000" +
    "\004\004\ufffb\001\002\000\006\006\021\015\020\001\002" +
    "\000\004\002\ufffe\001\002\000\004\025\025\001\002\000" +
    "\004\014\022\001\002\000\004\005\023\001\002\000\004" +
    "\002\ufffa\001\002\000\004\005\042\001\002\000\004\007" +
    "\026\001\002\000\004\012\027\001\002\000\022\026\036" +
    "\027\030\030\040\031\034\032\031\033\037\034\033\035" +
    "\032\001\002\000\004\012\uffee\001\002\000\004\012\uffeb" +
    "\001\002\000\004\012\uffe8\001\002\000\004\012\uffe9\001" +
    "\002\000\004\012\uffec\001\002\000\004\012\041\001\002" +
    "\000\004\012\uffef\001\002\000\004\012\uffea\001\002\000" +
    "\004\012\uffed\001\002\000\004\005\ufff0\001\002\000\004" +
    "\004\ufff8\001\002\000\004\004\ufff6\001\002\000\004\004" +
    "\226\001\002\000\004\004\ufff7\001\002\000\004\004\150" +
    "\001\002\000\004\004\140\001\002\000\004\004\062\001" +
    "\002\000\010\016\055\020\054\022\053\001\002\000\004" +
    "\004\ufff5\001\002\000\004\005\060\001\002\000\004\005" +
    "\057\001\002\000\004\005\056\001\002\000\004\004\uffe6" +
    "\001\002\000\004\004\uffca\001\002\000\004\004\uffad\001" +
    "\002\000\004\004\131\001\002\000\004\017\106\001\002" +
    "\000\004\004\uffe5\001\002\000\004\010\065\001\002\000" +
    "\022\050\075\051\100\052\102\053\074\054\077\071\101" +
    "\072\104\076\076\001\002\000\004\004\067\001\002\000" +
    "\004\006\071\001\002\000\004\004\uffe2\001\002\000\004" +
    "\017\072\001\002\000\004\005\073\001\002\000\004\004" +
    "\uffd7\001\002\000\004\011\uffd9\001\002\000\004\011\uffdc" +
    "\001\002\000\004\011\uffdd\001\002\000\004\011\uffd8\001" +
    "\002\000\004\011\uffdb\001\002\000\004\011\uffdf\001\002" +
    "\000\004\011\uffda\001\002\000\004\011\105\001\002\000" +
    "\004\011\uffde\001\002\000\004\004\uffe0\001\002\000\004" +
    "\025\107\001\002\000\004\007\112\001\002\000\004\005" +
    "\111\001\002\000\004\010\uffe1\001\002\000\004\012\113" +
    "\001\002\000\026\036\121\037\117\040\123\041\125\042" +
    "\122\043\115\044\116\045\120\046\126\047\114\001\002" +
    "\000\004\012\uffce\001\002\000\004\012\uffd0\001\002\000" +
    "\004\012\uffcd\001\002\000\004\012\uffd4\001\002\000\004" +
    "\012\uffcc\001\002\000\004\012\uffd5\001\002\000\004\012" +
    "\uffd1\001\002\000\004\012\uffd3\001\002\000\004\012\127" +
    "\001\002\000\004\012\uffd2\001\002\000\004\012\uffcf\001" +
    "\002\000\004\005\uffd6\001\002\000\004\004\uffe7\001\002" +
    "\000\006\006\133\017\106\001\002\000\004\004\uffe4\001" +
    "\002\000\004\016\134\001\002\000\004\005\135\001\002" +
    "\000\004\004\uffe3\001\002\000\004\004\ufff3\001\002\000" +
    "\004\004\ufff4\001\002\000\012\006\143\016\055\020\054" +
    "\022\053\001\002\000\006\002\ufff9\004\ufff9\001\002\000" +
    "\004\004\ufff2\001\002\000\004\015\144\001\002\000\004" +
    "\005\145\001\002\000\006\002\ufff1\004\ufff1\001\002\000" +
    "\004\004\uffc9\001\002\000\004\010\200\001\002\000\004" +
    "\021\156\001\002\000\004\004\154\001\002\000\004\004" +
    "\uffcb\001\002\000\004\004\uffc8\001\002\000\006\006\155" +
    "\021\156\001\002\000\004\020\176\001\002\000\004\025" +
    "\160\001\002\000\004\005\175\001\002\000\004\007\161" +
    "\001\002\000\004\012\162\001\002\000\022\055\167\056" +
    "\172\057\165\060\163\061\164\062\166\063\173\064\170" +
    "\001\002\000\004\012\uffb3\001\002\000\004\012\uffb2\001" +
    "\002\000\004\012\uffb4\001\002\000\004\012\uffb1\001\002" +
    "\000\004\012\uffb6\001\002\000\004\012\uffaf\001\002\000" +
    "\004\012\174\001\002\000\004\012\uffb5\001\002\000\004" +
    "\012\uffb0\001\002\000\004\005\uffb7\001\002\000\004\010" +
    "\uffc5\001\002\000\004\005\177\001\002\000\004\004\uffc7" +
    "\001\002\000\024\065\215\066\213\067\216\070\221\072" +
    "\217\073\207\074\214\075\211\077\210\001\002\000\004" +
    "\004\203\001\002\000\004\004\uffc6\001\002\000\004\006" +
    "\204\001\002\000\004\021\205\001\002\000\004\005\206" +
    "\001\002\000\004\004\uffb8\001\002\000\004\011\uffbf\001" +
    "\002\000\006\011\uffba\013\uffba\001\002\000\004\011\uffc0" +
    "\001\002\000\004\011\224\001\002\000\004\011\uffbc\001" +
    "\002\000\004\011\uffc1\001\002\000\004\011\uffbe\001\002" +
    "\000\004\011\uffbd\001\002\000\004\011\uffc2\001\002\000" +
    "\006\011\uffc3\013\222\001\002\000\004\011\uffbb\001\002" +
    "\000\004\077\223\001\002\000\006\011\uffb9\013\uffb9\001" +
    "\002\000\004\004\uffc4\001\002\000\004\004\uffac\001\002" +
    "\000\004\023\234\001\002\000\004\004\232\001\002\000" +
    "\004\004\uffae\001\002\000\004\004\uffab\001\002\000\006" +
    "\006\233\023\234\001\002\000\004\022\245\001\002\000" +
    "\004\024\235\001\002\000\004\007\241\001\002\000\004" +
    "\006\237\001\002\000\004\005\240\001\002\000\004\004" +
    "\uffa9\001\002\000\004\012\242\001\002\000\004\077\243" +
    "\001\002\000\004\012\244\001\002\000\004\006\uffa8\001" +
    "\002\000\004\005\246\001\002\000\004\004\uffaa\001\002" +
    "\000\004\005\250\001\002\000\004\004\ufffd\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\247\000\014\002\004\003\003\004\010\007\005\010" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\011\046\015\044\016" +
    "\047\030\042\031\045\043\051\044\043\001\001\000\010" +
    "\005\013\007\011\010\007\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\006\016\007\014\010\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\023\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\045\226\047\224\001\001" +
    "\000\002\001\001\000\010\032\150\034\145\035\146\001" +
    "\001\000\020\012\140\015\136\016\047\030\135\031\045" +
    "\043\141\044\043\001\001\000\010\017\060\021\062\022" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\020\127" +
    "\021\131\022\063\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\023\065\001\001\000\004\026\102\001\001" +
    "\000\004\024\067\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\025\107\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\027" +
    "\123\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\036\200\001\001" +
    "\000\002\001\001\000\010\033\151\034\152\035\146\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\040\156\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\042\170" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\041\211\051\217\001\001\000\004\037" +
    "\201\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\046\227" +
    "\047\230\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\050\235\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAcciones$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAcciones$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAcciones$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAcciones$actions {


    void print(String texto){ System.out.print(texto); } 


  private final ParserAcciones parser;

  /** Constructor */
  CUP$ParserAcciones$actions(ParserAcciones parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAcciones$do_action_part00000000(
    int                        CUP$ParserAcciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserAcciones$parser,
    java.util.Stack            CUP$ParserAcciones$stack,
    int                        CUP$ParserAcciones$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAcciones$result;

      /* select the action based on the action number */
      switch (CUP$ParserAcciones$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= cms EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		RESULT = start_val;
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAcciones$parser.done_parsing();
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // cms ::= accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("cms",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cms ::= acciones 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("cms",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // acciones ::= accionesIZQ accionesMID accionesDER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w3left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w3right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w3 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("acciones",1, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // accionesIZQ ::= IZQ ACCIS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesIZQ",2, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // accionesMID ::= accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesMID",3, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // accionesMID ::= accionesMID accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesMID",3, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // accionesDER ::= IZQ BARRA ACCIS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesDER",4, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // accion ::= accionIZQ accionMID accionDER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w3left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w3right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w3 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accion",5, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // accionIZQ ::= IZQ ACCI accionNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionIZQ",6, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accionMID ::= parametros 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // accionMID ::= atributos 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // accionMID ::= etiquetas 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // accionMID ::= accionMID parametros 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accionMID ::= accionMID atributos 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accionMID ::= accionMID etiquetas 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accionDER ::= IZQ BARRA ACCI DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionDER",8, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accionNombre ::= NOMBRE IGUAL COMI accionTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionNombre",9, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // accionTipo ::= SITE_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // accionTipo ::= SITE_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // accionTipo ::= PAGE_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // accionTipo ::= PAGE_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // accionTipo ::= PAGE_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accionTipo ::= COMP_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // accionTipo ::= COMP_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // accionTipo ::= COMP_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // parametros ::= parametrosIZQ parametrosMID parametrosDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametros",11, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // parametrosIZQ ::= IZQ PARAMS DER 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosIZQ",12, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // parametrosMID ::= parametro 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosMID",13, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // parametrosMID ::= parametrosMID parametro 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosMID",13, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // parametrosDER ::= IZQ BARRA PARAMS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosDER",14, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // parametro ::= parametroIZQ parametroMID parametroDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametro",15, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parametroIZQ ::= IZQ PARAM parametroNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroIZQ",16, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parametroMID ::= IZQCOR parametroValor DERCOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroMID",17, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parametroValor ::= MI_ID 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parametroValor ::= MI_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parametroValor ::= MI_FECHA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // parametroValor ::= UI_TITULO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parametroValor ::= UI_PARRAFO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // parametroValor ::= UI_IMAGEN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // parametroValor ::= UI_VIDEO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // parametroValor ::= UI_MENU 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // parametroDER ::= IZQ BARRA PARAM DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroDER",18, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // parametroNombre ::= NOMBRE IGUAL COMI parametroTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroNombre",19, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // parametroTipo ::= P_ID 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // parametroTipo ::= P_TITULO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // parametroTipo ::= P_SITIO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // parametroTipo ::= P_PADRE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // parametroTipo ::= P_PAGINA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // parametroTipo ::= P_CLASE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // parametroTipo ::= P_USER_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // parametroTipo ::= P_USER_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // parametroTipo ::= P_FECHA_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // parametroTipo ::= P_FECHA_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // atributos ::= atributosIZQ atributosMID atributosDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributos",22, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // atributosIZQ ::= IZQ ATRIBS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosIZQ",23, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // atributosMID ::= atributo 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosMID",24, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // atributosMID ::= atributosMID atributo 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosMID",24, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // atributosDER ::= IZQ BARRA ATRIBS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosDER",25, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // atributo ::= atributoIZQ atributoMID atributoDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributo",26, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // atributoIZQ ::= IZQ ATRIB atributoNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoIZQ",27, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // atributoMID ::= IZQCOR atributoValor DERCOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoMID",28, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // atributoValor ::= misEtiquetas 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // atributoValor ::= MI_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // atributoValor ::= MI_COLOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // atributoValor ::= MI_URL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // atributoValor ::= MI_NUMERO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // atributoValor ::= T_CENTRAR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // atributoValor ::= T_DERECHA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // atributoValor ::= T_IZQUIERDA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // atributoValor ::= T_JUSTIFICAR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // misEtiquetas ::= MI_ETIQUETA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("misEtiquetas",39, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // misEtiquetas ::= misEtiquetas OR MI_ETIQUETA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("misEtiquetas",39, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // atributoDER ::= IZQ BARRA ATRIB DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoDER",29, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // atributoNombre ::= NOMBRE IGUAL COMI atributoTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoNombre",30, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // atributoTipo ::= A_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // atributoTipo ::= A_ALIGN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // atributoTipo ::= A_COLOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // atributoTipo ::= A_ORIGEN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // atributoTipo ::= A_ALTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // atributoTipo ::= A_ANCHO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // atributoTipo ::= A_PADRE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // atributoTipo ::= A_ETIQS 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // etiquetas ::= etiquetasIZQ etiquetasMID etiquetasDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetas",33, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // etiquetasIZQ ::= IZQ ETIQS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasIZQ",34, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // etiquetasMID ::= etiqueta 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasMID",35, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // etiquetasMID ::= etiquetasMID etiqueta 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasMID",35, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // etiquetasDER ::= IZQ BARRA ETIQS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasDER",36, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // etiqueta ::= IZQ ETIQ etiquetaValor BARRA DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiqueta",37, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // etiquetaValor ::= VALOR IGUAL COMI MI_ETIQUETA COMI 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetaValor",38, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAcciones$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAcciones$do_action(
    int                        CUP$ParserAcciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserAcciones$parser,
    java.util.Stack            CUP$ParserAcciones$stack,
    int                        CUP$ParserAcciones$top)
    throws java.lang.Exception
    {
              return CUP$ParserAcciones$do_action_part00000000(
                               CUP$ParserAcciones$act_num,
                               CUP$ParserAcciones$parser,
                               CUP$ParserAcciones$stack,
                               CUP$ParserAcciones$top);
    }
}

}
