
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package josq.cms.lenguajes.parser;

import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAcciones extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserAccionesSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAcciones() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAcciones(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAcciones(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\136\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\002\003\000\002\003\005\000\002\003\004" +
    "\000\002\004\005\000\002\005\003\000\002\005\004\000" +
    "\002\006\006\000\002\007\005\000\002\010\006\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\004\000\002\011\004\000\002\011\004\000\002\011\004" +
    "\000\002\012\006\000\002\013\007\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\015\005\000\002\016\005\000\002\017\003" +
    "\000\002\017\004\000\002\020\006\000\002\021\005\000" +
    "\002\022\006\000\002\023\005\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\024\006\000\002\025\007\000\002\027\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\030\005" +
    "\000\002\031\005\000\002\032\003\000\002\032\004\000" +
    "\002\033\006\000\002\034\005\000\002\035\006\000\002" +
    "\036\005\000\002\041\003\000\002\041\003\000\002\041" +
    "\003\000\002\041\003\000\002\041\003\000\002\041\003" +
    "\000\002\041\003\000\002\041\003\000\002\041\003\000" +
    "\002\041\003\000\002\051\003\000\002\051\005\000\002" +
    "\037\006\000\002\040\007\000\002\042\003\000\002\042" +
    "\003\000\002\042\003\000\002\042\003\000\002\042\003" +
    "\000\002\042\003\000\002\042\003\000\002\042\003\000" +
    "\002\043\005\000\002\044\005\000\002\045\003\000\002" +
    "\045\004\000\002\046\006\000\002\047\007\000\002\050" +
    "\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\006\003\007\004\010\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\256\001\002\000\004\002\000" +
    "\001\002\000\006\002\ufffe\005\255\001\002\000\006\014" +
    "\253\015\021\001\002\000\006\003\052\004\044\001\002" +
    "\000\004\004\014\001\002\000\004\004\ufffa\001\002\000" +
    "\004\015\021\001\002\000\004\004\017\001\002\000\004" +
    "\004\ufff9\001\002\000\006\006\022\015\021\001\002\000" +
    "\004\002\ufffd\001\002\000\004\025\026\001\002\000\004" +
    "\014\023\001\002\000\004\005\024\001\002\000\004\002" +
    "\ufff8\001\002\000\004\005\043\001\002\000\004\007\027" +
    "\001\002\000\004\012\030\001\002\000\022\026\037\027" +
    "\031\030\040\031\035\032\032\033\041\034\034\035\033" +
    "\001\002\000\004\012\uffeb\001\002\000\004\012\uffe8\001" +
    "\002\000\004\012\uffe5\001\002\000\004\012\uffe6\001\002" +
    "\000\004\012\uffe9\001\002\000\004\012\042\001\002\000" +
    "\004\012\uffec\001\002\000\004\012\uffea\001\002\000\004" +
    "\012\uffe7\001\002\000\004\005\uffed\001\002\000\006\003" +
    "\ufff6\004\ufff6\001\002\000\010\016\223\020\222\022\220" +
    "\001\002\000\004\004\232\001\002\000\004\004\215\001" +
    "\002\000\004\004\ufff3\001\002\000\004\004\137\001\002" +
    "\000\004\004\060\001\002\000\004\005\055\001\002\000" +
    "\004\004\ufff5\001\002\000\004\004\ufff4\001\002\000\004" +
    "\004\uffef\001\002\000\004\004\uffc6\001\002\000\004\010" +
    "\110\001\002\000\004\021\066\001\002\000\004\004\064" +
    "\001\002\000\004\004\uffc8\001\002\000\004\004\uffc5\001" +
    "\002\000\006\006\065\021\066\001\002\000\004\020\106" +
    "\001\002\000\004\025\070\001\002\000\004\005\105\001" +
    "\002\000\004\007\071\001\002\000\004\012\072\001\002" +
    "\000\022\055\100\056\102\057\075\060\073\061\074\062" +
    "\076\063\103\064\077\001\002\000\004\012\uffaf\001\002" +
    "\000\004\012\uffae\001\002\000\004\012\uffb0\001\002\000" +
    "\004\012\uffad\001\002\000\004\012\uffab\001\002\000\004" +
    "\012\uffb2\001\002\000\004\012\104\001\002\000\004\012" +
    "\uffb1\001\002\000\004\012\uffac\001\002\000\004\005\uffb3" +
    "\001\002\000\004\010\uffc2\001\002\000\004\005\107\001" +
    "\002\000\004\004\uffc4\001\002\000\026\065\125\066\123" +
    "\067\127\070\132\071\124\072\130\073\117\074\126\075" +
    "\121\077\120\001\002\000\004\004\113\001\002\000\004" +
    "\004\uffc3\001\002\000\004\006\114\001\002\000\004\021" +
    "\115\001\002\000\004\005\116\001\002\000\004\004\uffb4" +
    "\001\002\000\004\011\uffbb\001\002\000\006\011\uffb6\013" +
    "\uffb6\001\002\000\004\011\uffbc\001\002\000\004\011\135" +
    "\001\002\000\004\011\uffb8\001\002\000\004\011\uffbf\001" +
    "\002\000\004\011\uffba\001\002\000\004\011\uffbd\001\002" +
    "\000\004\011\uffb9\001\002\000\004\011\uffbe\001\002\000" +
    "\006\011\uffc0\013\133\001\002\000\004\011\uffb7\001\002" +
    "\000\004\077\134\001\002\000\006\011\uffb5\013\uffb5\001" +
    "\002\000\004\004\uffc1\001\002\000\004\004\206\001\002" +
    "\000\004\017\163\001\002\000\004\004\uffe2\001\002\000" +
    "\004\010\142\001\002\000\022\050\152\051\155\052\157" +
    "\053\151\054\154\071\156\072\161\076\153\001\002\000" +
    "\004\004\144\001\002\000\004\006\146\001\002\000\004" +
    "\004\uffdf\001\002\000\004\017\147\001\002\000\004\005" +
    "\150\001\002\000\004\004\uffd4\001\002\000\004\011\uffd6" +
    "\001\002\000\004\011\uffd9\001\002\000\004\011\uffda\001" +
    "\002\000\004\011\uffd5\001\002\000\004\011\uffd8\001\002" +
    "\000\004\011\uffdc\001\002\000\004\011\uffd7\001\002\000" +
    "\004\011\162\001\002\000\004\011\uffdb\001\002\000\004" +
    "\004\uffdd\001\002\000\004\025\164\001\002\000\004\007" +
    "\167\001\002\000\004\005\166\001\002\000\004\010\uffde" +
    "\001\002\000\004\012\170\001\002\000\026\036\176\037" +
    "\174\040\200\041\202\042\177\043\172\044\173\045\175" +
    "\046\203\047\171\001\002\000\004\012\uffcb\001\002\000" +
    "\004\012\uffcd\001\002\000\004\012\uffca\001\002\000\004" +
    "\012\uffd1\001\002\000\004\012\uffc9\001\002\000\004\012" +
    "\uffd2\001\002\000\004\012\uffce\001\002\000\004\012\uffd0" +
    "\001\002\000\004\012\204\001\002\000\004\012\uffcf\001" +
    "\002\000\004\012\uffcc\001\002\000\004\005\uffd3\001\002" +
    "\000\004\004\uffe4\001\002\000\006\006\210\017\163\001" +
    "\002\000\004\004\uffe1\001\002\000\004\016\211\001\002" +
    "\000\004\005\212\001\002\000\004\004\uffe0\001\002\000" +
    "\004\004\ufff1\001\002\000\004\004\ufff2\001\002\000\012" +
    "\006\221\016\223\020\222\022\220\001\002\000\006\002" +
    "\ufff7\004\ufff7\001\002\000\004\004\ufff0\001\002\000\004" +
    "\005\230\001\002\000\004\015\226\001\002\000\004\005" +
    "\225\001\002\000\004\005\224\001\002\000\004\004\uffe3" +
    "\001\002\000\004\004\uffc7\001\002\000\004\005\227\001" +
    "\002\000\006\002\uffee\004\uffee\001\002\000\004\004\uffa9" +
    "\001\002\000\004\004\uffa8\001\002\000\004\023\240\001" +
    "\002\000\004\004\236\001\002\000\004\004\uffaa\001\002" +
    "\000\004\004\uffa7\001\002\000\006\006\237\023\240\001" +
    "\002\000\004\022\251\001\002\000\004\024\241\001\002" +
    "\000\004\007\245\001\002\000\004\006\243\001\002\000" +
    "\004\005\244\001\002\000\004\004\uffa5\001\002\000\004" +
    "\012\246\001\002\000\004\077\247\001\002\000\004\012" +
    "\250\001\002\000\004\006\uffa4\001\002\000\004\005\252" +
    "\001\002\000\004\004\uffa6\001\002\000\004\005\254\001" +
    "\002\000\004\004\ufffb\001\002\000\004\002\ufffc\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\014\002\004\003\003\004\011\007\005\010" +
    "\010\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\011" +
    "\045\015\052\016\047\030\053\031\050\043\046\044\044" +
    "\001\001\000\010\005\014\007\012\010\010\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\017\007\015" +
    "\010\010\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\024\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\045\232" +
    "\047\230\001\001\000\020\012\215\015\213\016\047\030" +
    "\212\031\050\043\216\044\044\001\001\000\002\001\001" +
    "\000\010\017\135\021\137\022\140\001\001\000\010\032" +
    "\060\034\055\035\056\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\036\110\001\001\000\002\001\001\000\010" +
    "\033\061\034\062\035\056\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\040\066\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\042\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\041\121" +
    "\051\130\001\001\000\004\037\111\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\020\204\021\206\022\140\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\023\142\001\001\000\004\026" +
    "\157\001\001\000\004\024\144\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\164\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\027\200\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\046\233\047\234\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\050" +
    "\241\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAcciones$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAcciones$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAcciones$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAcciones$actions {


    void print(String texto){ System.out.print(texto); } 


  private final ParserAcciones parser;

  /** Constructor */
  CUP$ParserAcciones$actions(ParserAcciones parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAcciones$do_action_part00000000(
    int                        CUP$ParserAcciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserAcciones$parser,
    java.util.Stack            CUP$ParserAcciones$stack,
    int                        CUP$ParserAcciones$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAcciones$result;

      /* select the action based on the action number */
      switch (CUP$ParserAcciones$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= cms EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		RESULT = start_val;
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAcciones$parser.done_parsing();
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // cms ::= accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("cms",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cms ::= acciones 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("cms",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cms ::= error 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		 print("@CMS "); 
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("cms",0, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // acciones ::= accionesIZQ accionesMID accionesDER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w3left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w3right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w3 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("acciones",1, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // acciones ::= error DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		 print("@ACCIONES> "); 
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("acciones",1, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // accionesIZQ ::= IZQ ACCIS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesIZQ",2, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // accionesMID ::= accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesMID",3, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // accionesMID ::= accionesMID accion 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesMID",3, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // accionesDER ::= IZQ BARRA ACCIS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionesDER",4, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accion ::= accionIZQ accionMID accionDER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)).value;
		int w2left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w2right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w2 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		int w3left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).left;
		int w3right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()).right;
		Object w3 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.peek()).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accion",5, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // accionIZQ ::= IZQ ACCI accionNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionIZQ",6, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // accionMID ::= parametros 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // accionMID ::= atributos 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accionMID ::= etiquetas 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accionMID ::= accionMID parametros 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accionMID ::= accionMID atributos 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accionMID ::= accionMID etiquetas 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // accionMID ::= error DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		 print("@ACCION<> "); 
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionMID",7, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // accionDER ::= IZQ BARRA ACCI DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionDER",8, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // accionNombre ::= NOMBRE IGUAL COMI accionTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionNombre",9, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // accionTipo ::= SITE_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // accionTipo ::= SITE_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accionTipo ::= PAGE_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // accionTipo ::= PAGE_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // accionTipo ::= PAGE_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // accionTipo ::= COMP_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // accionTipo ::= COMP_DEL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // accionTipo ::= COMP_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("accionTipo",10, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // parametros ::= parametrosIZQ parametrosMID parametrosDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametros",11, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // parametrosIZQ ::= IZQ PARAMS DER 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosIZQ",12, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // parametrosMID ::= parametro 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosMID",13, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parametrosMID ::= parametrosMID parametro 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosMID",13, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parametrosDER ::= IZQ BARRA PARAMS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametrosDER",14, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parametro ::= parametroIZQ parametroMID parametroDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametro",15, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parametroIZQ ::= IZQ PARAM parametroNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroIZQ",16, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parametroMID ::= IZQCOR parametroValor DERCOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroMID",17, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // parametroValor ::= MI_ID 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parametroValor ::= MI_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // parametroValor ::= MI_FECHA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // parametroValor ::= UI_TITULO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // parametroValor ::= UI_PARRAFO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // parametroValor ::= UI_IMAGEN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // parametroValor ::= UI_VIDEO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // parametroValor ::= UI_MENU 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroValor",20, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // parametroDER ::= IZQ BARRA PARAM DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroDER",18, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // parametroNombre ::= NOMBRE IGUAL COMI parametroTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroNombre",19, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // parametroTipo ::= P_ID 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // parametroTipo ::= P_TITULO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // parametroTipo ::= P_SITIO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // parametroTipo ::= P_PADRE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // parametroTipo ::= P_PAGINA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // parametroTipo ::= P_CLASE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // parametroTipo ::= P_USER_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // parametroTipo ::= P_USER_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // parametroTipo ::= P_FECHA_NEW 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // parametroTipo ::= P_FECHA_MOD 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("parametroTipo",21, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // atributos ::= atributosIZQ atributosMID atributosDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributos",22, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // atributosIZQ ::= IZQ ATRIBS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosIZQ",23, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // atributosMID ::= atributo 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosMID",24, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // atributosMID ::= atributosMID atributo 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosMID",24, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // atributosDER ::= IZQ BARRA ATRIBS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributosDER",25, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // atributo ::= atributoIZQ atributoMID atributoDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributo",26, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // atributoIZQ ::= IZQ ATRIB atributoNombre DER 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoIZQ",27, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // atributoMID ::= IZQCOR atributoValor DERCOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoMID",28, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // atributoValor ::= misEtiquetas 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // atributoValor ::= MI_ID 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // atributoValor ::= MI_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // atributoValor ::= MI_COLOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // atributoValor ::= MI_URL 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // atributoValor ::= MI_NUMERO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // atributoValor ::= T_CENTRAR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // atributoValor ::= T_DERECHA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // atributoValor ::= T_IZQUIERDA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // atributoValor ::= T_JUSTIFICAR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoValor",31, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // misEtiquetas ::= MI_ETIQUETA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("misEtiquetas",39, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // misEtiquetas ::= misEtiquetas OR MI_ETIQUETA 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("misEtiquetas",39, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // atributoDER ::= IZQ BARRA ATRIB DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoDER",29, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // atributoNombre ::= NOMBRE IGUAL COMI atributoTipo COMI 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoNombre",30, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // atributoTipo ::= A_TEXTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // atributoTipo ::= A_ALIGN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // atributoTipo ::= A_COLOR 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // atributoTipo ::= A_ORIGEN 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // atributoTipo ::= A_ALTO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // atributoTipo ::= A_ANCHO 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // atributoTipo ::= A_PADRE 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // atributoTipo ::= A_ETIQS 
            {
              Object RESULT =null;

              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("atributoTipo",32, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // etiquetas ::= etiquetasIZQ etiquetasMID etiquetasDER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetas",33, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // etiquetasIZQ ::= IZQ ETIQS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasIZQ",34, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // etiquetasMID ::= etiqueta 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasMID",35, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // etiquetasMID ::= etiquetasMID etiqueta 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasMID",35, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // etiquetasDER ::= IZQ BARRA ETIQS DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetasDER",36, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // etiqueta ::= IZQ ETIQ etiquetaValor BARRA DER 
            {
              Object RESULT =null;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiqueta",37, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // etiquetaValor ::= VALOR IGUAL COMI MI_ETIQUETA COMI 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).right;
		Object w1 = (Object)((java_cup.runtime.Symbol) CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-1)).value;
		  
              CUP$ParserAcciones$result = parser.getSymbolFactory().newSymbol("etiquetaValor",38, ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.elementAt(CUP$ParserAcciones$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAcciones$stack.peek()), RESULT);
            }
          return CUP$ParserAcciones$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAcciones$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAcciones$do_action(
    int                        CUP$ParserAcciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserAcciones$parser,
    java.util.Stack            CUP$ParserAcciones$stack,
    int                        CUP$ParserAcciones$top)
    throws java.lang.Exception
    {
              return CUP$ParserAcciones$do_action_part00000000(
                               CUP$ParserAcciones$act_num,
                               CUP$ParserAcciones$parser,
                               CUP$ParserAcciones$stack,
                               CUP$ParserAcciones$top);
    }
}

}
